const englishWords = [
  { easy: "Pidgeon", hard: "Dentist Drill" },
  { easy: "Snake", hard: "Blender" },
  { easy: "Mouse", hard: "Earthquake" },
  { easy: "Heartbeat", hard: "Zombie" },
  { easy: "Bell", hard: "Camera" },
  { easy: "Hiccup", hard: "Panda" },
  { easy: "Bee", hard: "Footsteps" },
  { easy: "Train", hard: "Broom" },
  { easy: "Dinosaur", hard: "Saxophone" },
  { easy: "Kiss", hard: "Tornado" },
  { easy: "Monster", hard: "Scissors" },
  { easy: "Police Car", hard: "Popcorn" },
  { easy: "Drinking", hard: "Boxing" },
  { easy: "Guitar", hard: "Bus" },
  { easy: "Doorbell", hard: "Cricket" },
  { easy: "Whip", hard: "Seagull" },
  { easy: "Fart", hard: "Bubbles" },
  { easy: "Rain", hard: "Chainsaw" },
  { easy: "Clock", hard: "Helicopter" },
  { easy: "Cat", hard: "Fireworks" },
  { easy: "Dog", hard: "Thunder" },
  { easy: "Wind", hard: "Motorcycle" },
  { easy: "Bird", hard: "Keyboard" },
  { easy: "Airplane", hard: "Water" },
  { easy: "Laugh", hard: "Explosion" },
  { easy: "Cough", hard: "Siren" },
  { easy: "Sneezing", hard: "Alarm" },
  { easy: "Typewriter", hard: "Chains" },
  { easy: "Clapping", hard: "Sea" },
  { easy: "Whistle", hard: "Elephant" },
  { easy: "Drums", hard: "Coffee Maker" },
  { easy: "Goat", hard: "Microwave" },
  { easy: "Rooster", hard: "Washing Machine" },
  { easy: "Pig", hard: "Hairdryer" },
  { easy: "Mosquito", hard: "Air Conditioner" },
  { easy: "Door", hard: "Car Crash" },
  { easy: "Tarzan", hard: "Michael Jackson" },
  { easy: "Yawn", hard: "Shower" },
  { easy: "Karete", hard: "Printer" },
];

export default englishWords;