const englishWords = [
  { easy: "Pidgeon", hard: "Dentist Drill" },
  { easy: "Snake", hard: "Blender" },
  { easy: "Mouse", hard: "Earthquake" },
  { easy: "Heartbeat", hard: "Zombie" },
  { easy: "Bell", hard: "Camera" },
  { easy: "Hiccup", hard: "Panda" },
  { easy: "Bee", hard: "Footsteps" },
  { easy: "Train", hard: "Broom" },
  { easy: "Dinosaur", hard: "Saxophone" },
  { easy: "Kiss", hard: "Tornado" },
  { easy: "Monster", hard: "Scissors" },
  { easy: "Police Car", hard: "Popcorn" },
  { easy: "Drinking", hard: "Boxing" },
  { easy: "Guitar", hard: "Bus" },
  { easy: "Doorbell", hard: "Cricket" },
  { easy: "Whip", hard: "Seagull" },
  { easy: "Fart", hard: "Bubbles" },
  { easy: "Rain", hard: "Chainsaw" },
  { easy: "Clock", hard: "Helicopter" },
  { easy: "Cat", hard: "Fireworks" },
  { easy: "Dog", hard: "Thunder" },
  { easy: "Wind", hard: "Motorcycle" },
  { easy: "Bird", hard: "Keyboard" },
  { easy: "Airplane", hard: "Water" },
  { easy: "Laugh", hard: "Explosion" },
  { easy: "Cough", hard: "Siren" },
  { easy: "Sneezing", hard: "Alarm" },
  { easy: "Typewriter", hard: "Chains" },
  { easy: "Clapping", hard: "Sea" },
  { easy: "Whistle", hard: "Elephant" },
  { easy: "Drums", hard: "Coffee Maker" },
  { easy: "Goat", hard: "Microwave" },
  { easy: "Rooster", hard: "Washing Machine" },
  { easy: "Pig", hard: "Hairdryer" },
  { easy: "Mosquito", hard: "Air Conditioner" },
  { easy: "Door", hard: "Car Crash" },
  { easy: "Tarzan", hard: "Michael Jackson" },
  { easy: "Yawn", hard: "Shower" },
  { easy: "Karete", hard: "Printer" },
  { easy: "Toaster", hard: "Barbecue" },
  { easy: "Beatboxing", hard: "Hospital" },
  { easy: "Opera", hard: "Oven" },
  { easy: "Woodpecker", hard: "Ice Hockey" },
  { easy: "Aerosol", hard: "Triangle" },
  { easy: "Shark", hard: "Wrestling" },
  { easy: "Baby", hard: "Darts" },
  { easy: "Harmonica", hard: "Bungee Jump" },
  { easy: "Gasp", hard: "Golf" },
  { easy: "Party", hard: "Champagne Cork" },
  { easy: "Baseball", hard: "Harp" },
  { easy: "Gorilla", hard: "Fire" },
  { easy: "Bomb", hard: "Weight lifting" },
  { easy: "Ghost", hard: "Piano" },
  { easy: "Rabbit", hard: "Crocodile" },
  { easy: "Donkey", hard: "Whale" },
  { easy: "Hamster", hard: "Television" },
  { easy: "Crying", hard: "Toilet" },
  { easy: "Balloon", hard: "Lightsaber" },
  { easy: "Wolf", hard: "Hammer" },
  { easy: "Robot", hard: "Restaurant" },
  { easy: "Spit", hard: "Giving Birth" },
  { easy: "Parrot", hard: "Electricity" },
  { easy: "Singing", hard: "Swimming" },
  { easy: "Tractor", hard: "Roller Coaster" },
  { easy: "Bazooka", hard: "Trampoline" },
  { easy: "Gong", hard: "Bowling" },
  { easy: "Burp", hard: "Vampire" },
  { easy: "Fight", hard: "Radio" },
  { easy: "Arrow", hard: "Waterfall" },
  { easy: "Witch", hard: "Spaceship" },
  { easy: "Cell Phone", hard: "Tap Dancing" },
  { easy: "Vomit", hard: "Light Switch" },
  { easy: "Mario Bros.", hard: "Sonic" },
  { easy: "Maracas", hard: "Giant" },
  { easy: "Turkey", hard: "River" },
];

export default englishWords;

