const spanishWords = [
  { easy: "Paloma", hard: "Taladro de dentista" },
  { easy: "Serpiente", hard: "Licuadora" },
  { easy: "Ratón", hard: "Terremoto" },
  { easy: "Latido del corazón", hard: "Zombi" },
  { easy: "Campana", hard: "Cámara" },
  { easy: "Hipo", hard: "Panda" },
  { easy: "Abeja", hard: "Pasos" },
  { easy: "Tren", hard: "Escoba" },
  { easy: "Dinosaurio", hard: "Saxofón" },
  { easy: "Beso", hard: "Tornado" },
  { easy: "Monstruo", hard: "Tijeras" },
  { easy: "Auto de policía", hard: "Palomitas de maíz" },
  { easy: "Beber", hard: "Boxeo" },
  { easy: "Guitarra", hard: "Autobús" },
  { easy: "Timbre", hard: "Grillo" },
  { easy: "Látigo", hard: "Gaviota" },
  { easy: "Pedo", hard: "Burbujas" },
  { easy: "Lluvia", hard: "Motosierra" },
  { easy: "Reloj", hard: "Helicóptero" },
  { easy: "Gato", hard: "Fuegos artificiales" },
  { easy: "Perro", hard: "Trueno" },
  { easy: "Viento", hard: "Motocicleta" },
  { easy: "Pájaro", hard: "Teclado" },
  { easy: "Avión", hard: "Agua" },
  { easy: "Risa", hard: "Explosión" },
  { easy: "Tos", hard: "Sirena" },
  { easy: "Estornudo", hard: "Alarma" },
  { easy: "Máquina de escribir", hard: "Cadenas" },
  { easy: "Aplausos", hard: "Mar" },
  { easy: "Silbido", hard: "Elefante" },
  { easy: "Tambores", hard: "Cafetera" },
  { easy: "Cabra", hard: "Microondas" },
  { easy: "Gallo", hard: "Lavadora" },
  { easy: "Cerdo", hard: "Secador de pelo" },
  { easy: "Mosquito", hard: "Aire acondicionado" },
  { easy: "Puerta", hard: "Accidente de auto" },
  { easy: "Tarzán", hard: "Michael Jackson" },
  { easy: "Bostezo", hard: "Ducha" },
  { easy: "Karate", hard: "Impresora" },
  { easy: "Tostadora", hard: "Barbacoa" },
  { easy: "Beatboxing", hard: "Hospital" },
  { easy: "Ópera", hard: "Horno" },
  { easy: "Pájaro Carpintero", hard: "Hockey" },
  { easy: "Aerosol", hard: "Triángulo" },
  { easy: "Tiburón", hard: "Lucha libre" },
  { easy: "Bebé", hard: "Dardos" },
  { easy: "Armónica", hard: "Salto Bungee" },
  { easy: "Jadeo", hard: "Golf" },
  { easy: "Fiesta", hard: "Corcho de champán" },
  { easy: "Béisbol", hard: "Arpa" },
  { easy: "Gorila", hard: "Fuego" },
  { easy: "Bomba", hard: "Levantamiento de pesas" },
  { easy: "Fantasma", hard: "Piano" },
  { easy: "Conejo", hard: "Cocodrilo" },
  { easy: "Burro", hard: "Ballena" },
  { easy: "Hámster", hard: "Televisión" },
  { easy: "Llanto", hard: "Inodoro" },
  { easy: "Globo", hard: "Sable de luz" },
  { easy: "Lobo", hard: "Martillo" },
  { easy: "Robot", hard: "Restaurante" },
  { easy: "Escupir", hard: "Dar a luz" },
  { easy: "Loro", hard: "Electricidad" },
  { easy: "Cantar", hard: "Nadar" },
  { easy: "Tractor", hard: "Montaña rusa" },
  { easy: "Bazuca", hard: "Trampolín" },
  { easy: "Gong", hard: "Bolos" },
  { easy: "Eructo", hard: "Vampiro" },
  { easy: "Pelea", hard: "Radio" },
  { easy: "Flecha", hard: "Cascada" },
  { easy: "Bruja", hard: "Nave espacial" },
  { easy: "Celular", hard: "Baile Tap" },
  { easy: "Vómito", hard: "Interruptor de luz" },
  { easy: "Mario Bros.", hard: "Sonic" },
  { easy: "Maracas", hard: "Gigante" },
  { easy: "Pavo", hard: "Río" }
];

export default spanishWords;