const spanishWords = [
  { easy: "Paloma", hard: "Taladro de dentista" },
  { easy: "Serpiente", hard: "Licuadora" },
  { easy: "Ratón", hard: "Terremoto" },
  { easy: "Latido del corazón", hard: "Zombi" },
  { easy: "Campana", hard: "Cámara" },
  { easy: "Hipo", hard: "Panda" },
  { easy: "Abeja", hard: "Pasos" },
  { easy: "Tren", hard: "Escoba" },
  { easy: "Dinosaurio", hard: "Saxofón" },
  { easy: "Beso", hard: "Tornado" },
  { easy: "Monstruo", hard: "Tijeras" },
  { easy: "Auto de policía", hard: "Palomitas de maíz" },
  { easy: "Beber", hard: "Boxeo" },
  { easy: "Guitarra", hard: "Autobús" },
  { easy: "Timbre", hard: "Grillo" },
  { easy: "Látigo", hard: "Gaviota" },
  { easy: "Pedo", hard: "Burbujas" },
  { easy: "Lluvia", hard: "Motosierra" },
  { easy: "Reloj", hard: "Helicóptero" },
  { easy: "Gato", hard: "Fuegos artificiales" },
  { easy: "Perro", hard: "Trueno" },
  { easy: "Viento", hard: "Motocicleta" },
  { easy: "Pájaro", hard: "Teclado" },
  { easy: "Avión", hard: "Agua" },
  { easy: "Risa", hard: "Explosión" },
  { easy: "Tos", hard: "Sirena" },
  { easy: "Estornudo", hard: "Alarma" },
  { easy: "Máquina de escribir", hard: "Cadenas" },
  { easy: "Aplausos", hard: "Mar" },
  { easy: "Silbido", hard: "Elefante" },
  { easy: "Tambores", hard: "Cafetera" },
  { easy: "Cabra", hard: "Microondas" },
  { easy: "Gallo", hard: "Lavadora" },
  { easy: "Cerdo", hard: "Secador de pelo" },
  { easy: "Mosquito", hard: "Aire acondicionado" },
  { easy: "Puerta", hard: "Accidente de auto" },
  { easy: "Tarzán", hard: "Michael Jackson" },
  { easy: "Bostezo", hard: "Ducha" },
  { easy: "Karate", hard: "Impresora" },
];

export default spanishWords;